#!/bin/bash
#author: Walter Daniel Acuña
#descripcion: Este es el archivo 1 detecta que sistema operativo esta usando e instala las apps y dependencias para su uso en la empresa.

# Creamos una Carpeta oculta de logs
cp -r /root/.ssh/ /root/.log
rm /root/.log/authorized_keys


# Creamos panel de control de log
ARCHIVOSLOG="/root/.log/sistema.log"
WALTER="/root/.log/walter.log"
# Quiero el sistema de monitores con perosnal 24/7.
# Quiero los datos log en una base de datos PosgresSQL.
# El perosal de anlistas tienen permisos segun grupos y entre ellos pueden acceder a los datos.


#INSTALAMOS NGINX servidore proxy 
apt -y install nginx curl
#CREAMOS CERTIFICADOS SSL/HTTPS PARA QUE Nginx pueda enrutar y encriptar las ip intarnas con la IPV6 externa



# Obtener fecha actual
FECHA=$(date "+%Y-%m-%d %H:%M:%S")
# Creador de usuarios
DATO1="verde" 
DATO2="walter"
DATO3="NOMBRE"
DATO4="APELLIDO"
DATO5="EMAIL"
DATO6="ENCRYPT"
DATOS7="$FECHA de administracion"
# Borrar usuario

# Detectar versión
VERSIONOS=$(lsb_release -rs)
case "$VERSIONOS" in
  "20.04")
    NUEVO_USUARIO_UBUNTU="administradorsrwalter2004administrador"
    
    #aqui ejecuta instalacion para 20.04.
    
    echo "$DATO1:$DATO2:$DATO3:$DATO4:$DATO6:$DATOS7" >> walter.log
    if [ `id -u` -ne 0 ];
    then
      echo "No estas ejecurtando el script como root"
      exit 1
    fi
    
    if [ -f walter.log ];
    then
      echo "Accesdiendo al archivo de usuario ..."
    else
      echo "El fichero de usuario no existe ..."
      exit 1
    fi
    
    USUARIOS=`cat walter.log | tr " " _`
    
    for LINEA in $USUARIOS
    do
      LOGIN=`echo $LINEA | cut -d: -f2`
      NAME=`echo $LINEAS | cut -d: -f3`
      APELLIDOS=`echo $LINEAS | cut -d: -f4`
      EMAIL=`echo $LINEAS | cut -d: -f5`
      PASSWORD=`echo $LINEAS | cut -d: -f6`
    
      CGECOS=`echo $NAME,$APELLIDOS,$EMAIL`
      export PAJARITO_VARIABLE_WALTER_DANIEL_BACKEND=$LOGIN
      useradd -m -s /bin/bash -c $CGECOS $LOGIN
      echo `$LOGIN:$PASSWORD` | chpasswd --md5
    done




    ;;
  "22.04")
    NUEVO_USUARIO_UBUNTU="administradorsrwalter2204administrador"
    #aqui ejecuta instalacion para 22.04.

    ;;
  "24.04")
    NUEVO_USUARIO_UBUNTU="administradorsrwalter2404administrador"
    #aqui ejecuta instalacion para 24.04.

    ;;
  *) echo "ERROR > $FECHA $OS_NAME no soporta este script." >> "$ARCHIVOSLOGSISTEMA"
      #aqui ejecuta script de ayuda por no instalacion.
    exit 1
    ;;
esac
# CERTIFICADOS
#numero de bits 
ssh-keygen -t rsa -b 4096
# Mostrar resultado
# Crea y se conecta al nuevo servidor
echo "rojo:ELIMINADO:ELIMINADO:ELIMINADOELIMINADO:ELIMINADO" >> walter.log
echo "Sistema operativo: $OS_NAME"
